parameters:
  artifactName: 'MpqNameBreaker'

jobs:
- job: Build
  steps:
    - task: UseDotNet@2
      displayName: 'Use .NET 6.0.x SDK'
      inputs:
        packageType: 'sdk'
        version: 6.0.x
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        command: 'build'
        projects: '**/MpqNameBreaker.csproj'
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
    - publish: '$(Build.artifactStagingDirectory)'
      artifact: ${{ parameters.artifactName }}
